# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labellog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, max_length=1, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('event_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LabelLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('actor1', models.CharField(blank=True, max_length=45, null=True)),
                ('actor2', models.CharField(blank=True, max_length=45, null=True)),
                ('event_type', models.CharField(blank=True, max_length=45, null=True)),
                ('event_subtype', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taskinstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.IntegerField()),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'TaskInstances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=45, null=True)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
