# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labellog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='taskinstances',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
